name: Virgil
version: 1.1
authors: [trainphreak,imarki360]
softdepend: [Vault]
main: com.grid_tronix.the.virgil.VirgilMain
commands:
  virgil:
    description: Base command for Virgil
permissions:
  virgil.trigger:
    description: Players with this permission are able to trigger a config-defined response
    default: false
  virgil.trigger.bot:
    description: Players with this permission are able to trigger a chatbot response
    default: false
    children:
      virgil.trigger: true
  virgil.reload:
    default: false
  virgil.shutup:
    description: Players with this permission are able to turn off all Cleverbot responses
    default: false